import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    home: "Home", about: "About", leadership: "Leadership", programs: "Programs", events: "Events", contact: "Contact", farmerLogin: "Farmer Login", language: "ಕನ್ನಡ",
    tag: "KARNATAKA'S FARMER SANGA", heroTitle: "Support for every farmer. Progress for every village.", heroText: "Karunada Raitha Jana Abiruddhi Sanga connects farmers with training, schemes, local events and trusted support.", access: "Access Farmer Services", learn: "Learn about the Sanga", simple: "Farmer services, made simple", easyLogin: "Easy mobile login", otpInfo: "Use a one-time code sent to your phone.", secure: "Private and secure", secureInfo: "Your information is only used to support your farming needs.", adminSignIn: "Sanga administrator sign in",
    aboutTitle: "About KRJS", aboutText: "Karunada Raitha Jana Abiruddhi Sanga (KRJS) is committed to empowering farmers across Karnataka through education, awareness, sustainable agriculture, innovation, government scheme support and rural development.", mission: "Our Mission", missionText: "Empower farmers through education, sustainable agriculture, innovation and community development.", vision: "Our Vision", visionText: "Build a prosperous Karnataka where every farmer has access to opportunities, technology and support.", values: "Our Values", valuesText: "Unity, Transparency, Integrity, Sustainability and Service towards every farming family.",
    impact: "Our Impact", impactText: "Together we are creating a stronger farming community.", farmers: "Farmers Connected", districts: "Districts Covered", programsConducted: "Programs Conducted", eventsOrganized: "Events Organized", leadershipTitle: "Leadership Team", leadershipText: "Meet the dedicated leaders guiding Karunada Raitha Jana Abiruddhi Sanga.", viewProfile: "View Profile", eventsTitle: "Upcoming Events", eventsText: "Stay connected with our upcoming activities and farmer programs.", register: "Register", worksTitle: "Our Works & Achievements", worksText: "Dedicated to improving the lives of farmers through education, support, and sustainable initiatives.",
    helpTag: "WE ARE HERE TO HELP", helpTitle: "Talk to your Sanga", helpText: "Contact us for training, government scheme guidance, event registration and local farmer support.", call: "Call us", email: "Email support", whatsapp: "WhatsApp support", comingSoon: "Coming soon", karnataka: "Karnataka", centres: "District support centres",
    farmer: "Farmer", admin: "Admin", farmerServicesLogin: "Farmer services login", administration: "Sanga administration", farmerLoginInfo: "Log in with your mobile number to see trainings, schemes, registrations and support requests.", mobile: "Mobile number", mobilePlaceholder: "10-digit mobile number", sendOtp: "Send one-time code", google: "Continue with Google", adminInfo: "Restricted to authorised Sanga staff. Multi-factor authentication is required.", workEmail: "Work email", password: "Password", passwordPlaceholder: "Enter your password", continueMfa: "Continue to MFA", back: "Back", mfaInfo: "Enter the 6-digit code from your authenticator app.", authCode: "Authentication code", verify: "Verify and sign in", recovery: "Use a recovery code if you cannot access your authenticator.", demoReady: "Demo access ready", demoText: "This screen is ready for a secure authentication service to be connected.", farmerDashboard: "Farmer dashboard:", farmerDashboardText: "schemes, events, support and profile.", adminDashboard: "Admin dashboard:", adminDashboardText: "members, events, content and reports.", close: "Close",
    organic: "Organic Farming Training", organicText: "Providing practical training on organic and sustainable farming methods.", awareness: "Farmer Awareness Camps", awarenessText: "Conducting awareness programs across Karnataka to educate farmers.", water: "Water Conservation", waterText: "Promoting rainwater harvesting and efficient irrigation techniques.", schemes: "Government Scheme Assistance", schemesText: "Helping farmers access government schemes, subsidies, and benefits.", workshop: "Organic Farming Workshop", workshopText: "A one-day workshop on sustainable and organic farming practices.", camp: "Farmer Awareness Camp", campText: "Guidance on government schemes, crop insurance, and subsidies.", seminar: "Water Conservation Seminar", seminarText: "Learning efficient irrigation and rainwater harvesting techniques.", president: "President", vicePresident: "Vice President", secretary: "Secretary", bengaluru: "Bengaluru", mysuru: "Mysuru", tumakuru: "Tumakuru",
    uspTag: "OUR UNIQUE PROMISE", uspTitle: "One Sanga Seva Card. Every farmer service in one place.", uspText: "Use one mobile number to discover relevant schemes, ask your local coordinator for help, and track every request in Kannada or English.", schemeMatch: "Personalised scheme match", schemeMatchText: "Find support based on your crop, village and farming needs.", localHelp: "Local coordinator help", localHelpText: "Reach the right Sanga representative in your district.", trackStatus: "Track every request", trackStatusText: "See clear updates for applications, training and support requests.",
    welcomeFarmer: "Welcome, Farmer", farmerSubtitle: "Your Sanga Seva Card keeps your farming support in one place.", welcomeAdmin: "Sanga Admin Dashboard", adminSubtitle: "Manage farmers, services and community programs securely.", myServices: "My services", findSchemes: "Find schemes", requestHelp: "Request help", myEvents: "My events", myProfile: "My profile", requestStatus: "Request status", matchedSchemes: "Matched schemes", nextTraining: "Next training", localCoordinator: "Your local coordinator", activeRequests: "Active requests", members: "Members", registrations: "Registrations", content: "Content", reports: "Reports", pending: "Pending", inProgress: "In progress", completed: "Completed", viewAll: "View all", logout: "Back to website", openDashboard: "Open dashboard", quickHelp: "Quick help", helpQuestion: "What do you need help with?", submitRequest: "Submit request", cropInsurance: "Crop insurance", irrigation: "Irrigation", subsidy: "Subsidy / scheme", training: "Training", memberRecords: "Farmer records", eventManagement: "Event management", schemeUpdates: "Scheme updates", viewReport: "View report",
    addEventTitle: "Add an event", addEventSubtitle: "Publish an upcoming event and its location.", eventName: "Event name", eventNamePlaceholder: "e.g. Farmer training", eventDate: "Event date", eventLocation: "Event location", eventLocationPlaceholder: "Village, town or venue", descriptionLabel: "Description", descriptionPlaceholder: "Brief event details", publishEventBtn: "Publish event", eventPublishedMsg: "Event published. Its location is now shown on the website.", publishedEventsTitle: "Published events", eventsVisibleText: "events currently visible on the website.",
    active: "Active", confirmed: "Confirmed", applyNow: "Apply Now", applied: "Applied", registered: "You are registered!", farmerName: "Farmer Name", requestType: "Request Type", coordinator: "Coordinator", department: "Department", benefit: "Benefit", action: "Action", venue: "Venue"
  },
  kn: {
    home: "ಮುಖಪುಟ", about: "ನಮ್ಮ ಬಗ್ಗೆ", leadership: "ನಾಯಕತ್ವ", programs: "ಕಾರ್ಯಕ್ರಮಗಳು", events: "ಕಾರ್ಯಕ್ರಮ", contact: "ಸಂಪರ್ಕ", farmerLogin: "ರೈತರ ಲಾಗಿನ್", language: "English",
    tag: "ಕರ್ನಾಟಕದ ರೈತ ಸಂಘ", heroTitle: "ಪ್ರತಿ ರೈತನಿಗೆ ಬೆಂಬಲ. ಪ್ರತಿ ಹಳ್ಳಿಗೆ ಪ್ರಗತಿ.", heroText: "ಕರುನಾಡ ರೈತ ಜನ ಅಭಿವೃದ್ಧಿ ಸಂಘವು ತರಬೇತಿ, ಯೋಜನೆಗಳು, ಸ್ಥಳೀಯ ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ ಸಹಾಯದೊಂದಿಗೆ ರೈತರನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.", access: "ರೈತ ಸೇವೆಗಳನ್ನು ಪಡೆಯಿರಿ", learn: "ಸಂಘದ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ", simple: "ರೈತ ಸೇವೆಗಳು, ಸುಲಭವಾಗಿ", easyLogin: "ಸರಳ ಮೊಬೈಲ್ ಲಾಗಿನ್", otpInfo: "ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಬರುವ ಒಂದು-ಬಾರಿ ಕೋಡ್ ಬಳಸಿ.", secure: "ಖಾಸಗಿ ಮತ್ತು ಸುರಕ್ಷಿತ", secureInfo: "ನಿಮ್ಮ ಕೃಷಿ ಅಗತ್ಯಗಳ ಬೆಂಬಲಕ್ಕಾಗಿ ಮಾತ್ರ ಮಾಹಿತಿಯನ್ನು ಬಳಸಲಾಗುತ್ತದೆ.", adminSignIn: "ಸಂಘ ನಿರ್ವಾಹಕರ ಲಾಗಿನ್",
    aboutTitle: "ಕೆಆರ್‌ಜೆಎಸ್ ಬಗ್ಗೆ", aboutText: "ಕರುನಾಡ ರೈತ ಜನ ಅಭಿವೃದ್ಧಿ ಸಂಘವು ಕರ್ನಾಟಕದ ರೈತರನ್ನು ಶಿಕ್ಷಣ, ಅರಿವು, ಸುಸ್ಥಿರ ಕೃಷಿ, ಹೊಸತನ, ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಸಹಾಯ ಮತ್ತು ಗ್ರಾಮೀಣ ಅಭಿವೃದ್ಧಿಯ ಮೂಲಕ ಸಬಲೀಕರಣಗೊಳಿಸಲು ಬದ್ಧವಾಗಿದೆ.", mission: "ನಮ್ಮ ಧ್ಯೇಯ", missionText: "ಶಿಕ್ಷಣ, ಸುಸ್ಥಿರ ಕೃಷಿ, ಹೊಸತನ ಮತ್ತು ಸಮುದಾಯ ಅಭಿವೃದ್ಧಿಯ ಮೂಲಕ ರೈತರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು.", vision: "ನಮ್ಮ ದೃಷ್ಟಿ", visionText: "ಪ್ರತಿ ರೈತನಿಗೆ ಅವಕಾಶ, ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಬೆಂಬಲ ದೊರೆಯುವ ಸಮೃದ್ಧ ಕರ್ನಾಟಕ ನಿರ್ಮಿಸುವುದು.", values: "ನಮ್ಮ ಮೌಲ್ಯಗಳು", valuesText: "ಪ್ರತಿ ರೈತ ಕುಟುಂಬದ ಕಡೆಗೆ ಏಕತೆ, ಪಾರದರ್ಶಕತೆ, ಪ್ರಾಮಾಣಿಕತೆ, ಸುಸ್ಥಿರತೆ ಮತ್ತು ಸೇವೆ.",
    impact: "ನಮ್ಮ ಪ್ರಭಾವ", impactText: "ಒಟ್ಟಾಗಿ ನಾವು ಬಲವಾದ ಕೃಷಿ ಸಮುದಾಯವನ್ನು ನಿರ್ಮಿಸುತ್ತಿದ್ದೇವೆ.", farmers: "ಸಂಪರ್ಕದಲ್ಲಿರುವ ರೈತರು", districts: "ಒಳಗೊಂಡ ಜಿಲ್ಲೆಗಳು", programsConducted: "ನಡೆಸಿದ ಕಾರ್ಯಕ್ರಮಗಳು", eventsOrganized: "ಆಯೋಜಿಸಿದ ಕಾರ್ಯಕ್ರಮಗಳು", leadershipTitle: "ನಾಯಕತ್ವ ತಂಡ", leadershipText: "ಕರುನಾಡ ರೈತ ಜನ ಅಭಿವೃದ್ಧಿ ಸಂಘವನ್ನು ಮುನ್ನಡೆಸುವ ಸಮರ್ಪಿತ ನಾಯಕರನ್ನು ಭೇಟಿ ಮಾಡಿ.", viewProfile: "ಪ್ರೊಫೈಲ್ ನೋಡಿ", eventsTitle: "ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮಗಳು", eventsText: "ನಮ್ಮ ಮುಂಬರುವ ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ರೈತ ಕಾರ್ಯಕ್ರಮಗಳೊಂದಿಗೆ ಸಂಪರ್ಕದಲ್ಲಿರಿ.", register: "ನೋಂದಣಿ", worksTitle: "ನಮ್ಮ ಕೆಲಸಗಳು ಮತ್ತು ಸಾಧನೆಗಳು", worksText: "ಶಿಕ್ಷಣ, ಬೆಂಬಲ ಮತ್ತು ಸುಸ್ಥಿರ ಉಪಕ್ರಮಗಳ ಮೂಲಕ ರೈತರ ಜೀವನ ಸುಧಾರಣೆಗೆ ಸಮರ್ಪಿತರು.",
    helpTag: "ನಾವು ಸಹಾಯಕ್ಕೆ ಇಲ್ಲಿದ್ದೇವೆ", helpTitle: "ನಿಮ್ಮ ಸಂಘದೊಂದಿಗೆ ಮಾತನಾಡಿ", helpText: "ತರಬೇತಿ, ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಮಾರ್ಗದರ್ಶನ, ಕಾರ್ಯಕ್ರಮ ನೋಂದಣಿ ಮತ್ತು ಸ್ಥಳೀಯ ರೈತ ಬೆಂಬಲಕ್ಕಾಗಿ ಸಂಪರ್ಕಿಸಿ.", call: "ನಮಗೆ ಕರೆ ಮಾಡಿ", email: "ಇಮೇಲ್ ಸಹಾಯ", whatsapp: "ವಾಟ್ಸ್ಆ್ಯಪ್ ಸಹಾಯ", comingSoon: "ಶೀಘ್ರದಲ್ಲೇ", karnataka: "ಕರ್ನಾಟಕ", centres: "ಜಿಲ್ಲಾ ಬೆಂಬಲ ಕೇಂದ್ರಗಳು",
    farmer: "ರೈತ", admin: "ನಿರ್ವಾಹಕ", farmerServicesLogin: "ರೈತ ಸೇವೆಗಳ ಲಾಗಿನ್", administration: "ಸಂಘ ನಿರ್ವಹಣೆ", farmerLoginInfo: "ತರಬೇತಿ, ಯೋಜನೆಗಳು, ನೋಂದಣಿಗಳು ಮತ್ತು ಸಹಾಯ ವಿನಂತಿಗಳನ್ನು ನೋಡಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ಲಾಗಿನ್ ಮಾಡಿ.", mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ", mobilePlaceholder: "10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ", sendOtp: "ಒನ್-ಟೈಮ್ ಕೋಡ್ ಕಳುಹಿಸಿ", google: "Google ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ", adminInfo: "ಅಧಿಕೃತ ಸಂಘ ಸಿಬ್ಬಂದಿಗೆ ಮಾತ್ರ. ಬಹು-ಹಂತದ ದೃಢೀಕರಣ ಅಗತ್ಯವಿದೆ.", workEmail: "ಕೆಲಸದ ಇಮೇಲ್", password: "ಪಾಸ್ವರ್ಡ್", passwordPlaceholder: "ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ", continueMfa: "MFA ಗೆ ಮುಂದುವರಿಯಿರಿ", back: "ಹಿಂದೆ", mfaInfo: "ನಿಮ್ಮ ದೃಢೀಕರಣ ಅಪ್ಲಿಕೇಶನ್‌ನ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ.", authCode: "ದೃಢೀಕರಣ ಕೋಡ್", verify: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ", recovery: "ದೃಢೀಕರಣ ಅಪ್ಲಿಕೇಶನ್ ಲಭ್ಯವಿಲ್ಲದಿದ್ದರೆ ಮರುಪಡೆಯುವ ಕೋಡ್ ಬಳಸಿ.", demoReady: "ಡೆಮೊ ಪ್ರವೇಶ ಸಿದ್ಧವಾಗಿದೆ", demoText: "ಸುರಕ್ಷಿತ ದೃಢೀಕರಣ ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸಲು ಈ ಪರದೆ ಸಿದ್ಧವಾಗಿದೆ.", farmerDashboard: "ರೈತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್:", farmerDashboardText: "ಯೋಜನೆಗಳು, ಕಾರ್ಯಕ್ರಮಗಳು, ಬೆಂಬಲ ಮತ್ತು ಪ್ರೊಫೈಲ್.", adminDashboard: "ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್:", adminDashboardText: "ಸದಸ್ಯರು, ಕಾರ್ಯಕ್ರಮಗಳು, ವಿಷಯ ಮತ್ತು ವರದಿಗಳು.", close: "ಮುಚ್ಚಿ",
    organic: "ಸಾವಯವ ಕೃಷಿ ತರಬೇತಿ", organicText: "ಸಾವಯವ ಮತ್ತು ಸುಸ್ಥಿರ ಕೃಷಿ ವಿಧಾನಗಳ ಪ್ರಾಯೋಗಿಕ ತರಬೇತಿ.", awareness: "ರೈತ ಅರಿವು ಶಿಬಿರಗಳು", awarenessText: "ರೈತರಿಗೆ ಶಿಕ್ಷಣ ನೀಡಲು ಕರ್ನಾಟಕದಾದ್ಯಂತ ಅರಿವು ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನಡೆಸುವುದು.", water: "ನೀರಿನ ಸಂರಕ್ಷಣೆ", waterText: "ಮಳೆನೀರು ಕೊಯ್ಲು ಮತ್ತು ದಕ್ಷ ನೀರಾವರಿ ತಂತ್ರಗಳನ್ನು ಉತ್ತೇಜಿಸುವುದು.", schemes: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಸಹಾಯ", schemesText: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು, ಸಬ್ಸಿಡಿಗಳು ಮತ್ತು ಪ್ರಯೋಜನಗಳನ್ನು ಪಡೆಯಲು ರೈತರಿಗೆ ಸಹಾಯ.", workshop: "ಸಾವಯವ ಕೃಷಿ ಕಾರ್ಯಾಗಾರ", workshopText: "ಸುಸ್ಥಿರ ಮತ್ತು ಸಾವಯವ ಕೃಷಿ ಅಭ್ಯಾಸಗಳ ಒಂದು ದಿನದ ಕಾರ್ಯಾಗಾರ.", camp: "ರೈತ ಅರಿವು ಶಿಬಿರ", campText: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು, ಬೆಳೆ ವಿಮೆ ಮತ್ತು ಸಬ್ಸಿಡಿಗಳ ಬಗ್ಗೆ ಮಾರ್ಗದರ್ಶನ.", seminar: "ನೀರಿನ ಸಂರಕ್ಷಣೆ ವಿಚಾರ ಸಂಕಿರಣ", seminarText: "ದಕ್ಷ ನೀರಾವರಿ ಮತ್ತು ಮಳೆನೀರು ಕೊಯ್ಲಿನ ಕಲಿಕೆ.", president: "ಅಧ್ಯಕ್ಷರು", vicePresident: "ಉಪಾಧ್ಯಕ್ಷರು", secretary: "ಕಾರ್ಯದರ್ಶಿ", bengaluru: "ಬೆಂಗಳೂರು", mysuru: "ಮೈಸೂರು", tumakuru: "ತುಮಕೂರು",
    uspTag: "ನಮ್ಮ ವಿಶೇಷ ಭರವಸೆ", uspTitle: "ಒಂದು ಸಂಘ ಸೇವಾ ಕಾರ್ಡ್. ಪ್ರತಿಯೊಂದು ರೈತ ಸೇವೆಯೂ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.", uspText: "ಒಂದು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ನಿಮಗೆ ಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ತಿಳಿಯಿರಿ, ಸ್ಥಳೀಯ ಸಂಯೋಜಕರ ಸಹಾಯ ಪಡೆಯಿರಿ ಮತ್ತು ಪ್ರತಿಯೊಂದು ವಿನಂತಿಯ ಸ್ಥಿತಿಯನ್ನು ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ತಿಳಿಯಿರಿ.", schemeMatch: "ನಿಮಗಾಗಿ ಯೋಜನೆಗಳ ಹೊಂದಾಣಿಕೆ", schemeMatchText: "ನಿಮ್ಮ ಬೆಳೆ, ಹಳ್ಳಿ ಮತ್ತು ಕೃಷಿ ಅಗತ್ಯದ ಆಧಾರದ ಮೇಲೆ ಸಹಾಯ ಪಡೆಯಿರಿ.", localHelp: "ಸ್ಥಳೀಯ ಸಂಯೋಜಕರ ಸಹಾಯ", localHelpText: "ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಸರಿಯಾದ ಸಂಘ ಪ್ರತಿನಿಧಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.", trackStatus: "ಪ್ರತಿ ವಿನಂತಿಯ ಸ್ಥಿತಿ ತಿಳಿಯಿರಿ", trackStatusText: "ಅರ್ಜಿ, ತರಬೇತಿ ಮತ್ತು ಸಹಾಯ ವಿನಂತಿಗಳ ಸ್ಪಷ್ಟ ನವೀಕರಣ ಪಡೆಯಿರಿ.",
    welcomeFarmer: "ಸ್ವಾಗತ ರೈತರೇ", farmerSubtitle: "ನಿಮ್ಮ ಸಂಘ ಸೇವಾ ಕಾರ್ಡ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಕೃಷಿ ಬೆಂಬಲ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಸಿಗುತ್ತದೆ.", welcomeAdmin: "ಸಂಘ ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", adminSubtitle: "ರೈತರು, ಸೇವೆಗಳು ಮತ್ತು ಸಮುದಾಯ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ನಿರ್ವಹಿಸಿ.", myServices: "ನನ್ನ ಸೇವೆಗಳು", findSchemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ", requestHelp: "ಸಹಾಯ ಕೇಳಿ", myEvents: "ನನ್ನ ಕಾರ್ಯಕ್ರಮಗಳು", myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್", requestStatus: "ವಿನಂತಿಯ ಸ್ಥಿತಿ", matchedSchemes: "ಹೊಂದುವ ಯೋಜನೆಗಳು", nextTraining: "ಮುಂದಿನ ತರಬೇತಿ", localCoordinator: "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಸಂಯೋಜಕ", activeRequests: "ಸಕ್ರಿಯ ವಿನಂತಿಗಳು", members: "ಸದಸ್ಯರು", registrations: "ನೋಂದಣಿಗಳು", content: "ವಿಷಯ", reports: "ವರದಿಗಳು", pending: "ಬಾಕಿ ಇದೆ", inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ", completed: "ಪೂರ್ಣಗೊಂಡಿದೆ", viewAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ", logout: "ವೆಬ್‌ಸೈಟ್‌ಗೆ ಹಿಂತಿರುಗಿ", openDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ತೆರೆಯಿರಿ", quickHelp: "ತ್ವರಿತ ಸಹಾಯ", helpQuestion: "ನಿಮಗೆ ಯಾವ ಸಹಾಯ ಬೇಕು?", submitRequest: "ವಿನಂತಿ ಕಳುಹಿಸಿ", cropInsurance: "ಬೆಳೆ ವಿಮೆ", irrigation: "ನೀರಾವರಿ", subsidy: "ಸಬ್ಸಿಡಿ / ಯೋಜನೆ", training: "ತರಬೇತಿ", memberRecords: "ರೈತ ದಾಖಲೆಗಳು", eventManagement: "ಕಾರ್ಯಕ್ರಮ ನಿರ್ವಹಣೆ", schemeUpdates: "ಯೋಜನೆ ನವೀಕರಣಗಳು", viewReport: "ವರದಿ ನೋಡಿ",
    addEventTitle: "ಕಾರ್ಯಕ್ರಮವನ್ನು ಸೇರಿಸಿ", addEventSubtitle: "ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮ ಮತ್ತು ಅದರ ಸ್ಥಳವನ್ನು ಪ್ರಕಟಿಸಿ.", eventName: "ಕಾರ್ಯಕ್ರಮದ ಹೆಸರು", eventNamePlaceholder: "ಉದಾಹರಣೆಗೆ: ರೈತರ ತರಬೇತಿ", eventDate: "ಕಾರ್ಯಕ್ರಮದ ದಿನಾಂಕ", eventLocation: "ಕಾರ್ಯಕ್ರಮದ ಸ್ಥಳ", eventLocationPlaceholder: "ಹಳ್ಳಿ, ಪಟ್ಟಣ ಅಥವಾ ಸ್ಥಳ", descriptionLabel: "ವಿವರಣೆ", descriptionPlaceholder: "ಕಾರ್ಯಕ್ರಮದ ಕಿರು ವಿವರಗಳು", publishEventBtn: "ಕಾರ್ಯಕ್ರಮವನ್ನು ಪ್ರಕಟಿಸಿ", eventPublishedMsg: "ಕಾರ್ಯಕ್ರಮವನ್ನು ಪ್ರಕಟಿಸಲಾಗಿದೆ. ಇದರ ಸ್ಥಳವನ್ನು ಈಗ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ.", publishedEventsTitle: "ಪ್ರಕಟಿತ ಕಾರ್ಯಕ್ರಮಗಳು", eventsVisibleText: "ಕಾರ್ಯಕ್ರಮಗಳು ಪ್ರಸ್ತುತ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಗೋಚರಿಸುತ್ತಿವೆ.",
    active: "ಸಕ್ರಿಯ", confirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ", applyNow: "ಈಗಲೇ ಅರ್ಜಿ ಹಾಕಿ", applied: "ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ", registered: "ನೋಂದಾಯಿಸಲಾಗಿದೆ!", farmerName: "ರೈತರ ಹೆಸರು", requestType: "ವಿನಂತಿಯ ವಿಧ", coordinator: "ಸಂಯೋಜಕರು", department: "ಇಲಾಖೆ", benefit: "ಪ್ರಯೋಜನ", action: "ಕ್ರಮ", venue: "ಸ್ಥಳ"
  }
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");
  const t = (key) => translations[language][key] ?? key;
  return (
    <LanguageContext.Provider value={{ language, t, toggle: () => setLanguage((value) => value === "en" ? "kn" : "en") }}>
      {children}
    </LanguageContext.Provider>
  );
}
export const useLanguage = () => useContext(LanguageContext);
